# Generated by Django 6.0.5 on 2026-09-24 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0002_project_proj_company_del_status_idx'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['company', 'is_deleted', 'status'], name='task_company_del_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['company', 'assigned_to', 'is_deleted'], name='task_company_assignee_idx'),
        ),
    ]
